SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER > 3000
INTERSECT
SELECT FLAVOR
FROM ICECREAM_INFO
WHERE INGREDIENT_TYPE = 'fruit_based'

-- TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = fruit_based
-- 총 주문량이 큰 순서대로 조회
